[package]
name = "Poll_app"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web="4"
actix-rt="1.0"
sqlx = { version = "0.7", features = ["runtime-tokio", "postgres", "macros"] }


[profile.dev]
incremental = true

